# Generated by Django 5.2.4 on 2025-10-15 11:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Haydovchi ismi')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqam')),
                ('vehicle_info', models.CharField(max_length=255, verbose_name='Transport ma’lumotlari')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('is_online', models.BooleanField(default=False, verbose_name='Onlaynmi?')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Reyting')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Haydovchi',
                'verbose_name_plural': 'Haydovchilar',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Menyu nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Menyu',
                'verbose_name_plural': 'Menyular',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Restoran nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqam')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Restoran',
                'verbose_name_plural': 'Restoranlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='To‘liq ism')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqam')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Taom nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjudmi?')),
                ('prep_time_minutes', models.PositiveIntegerField(default=10, verbose_name='Tayyorlanish vaqti (daqiqa)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurant.menu', verbose_name='Menyu')),
            ],
            options={
                'verbose_name': 'Taom',
                'verbose_name_plural': 'Taomlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(verbose_name='Yetkazib berish manzili')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Umumiy summa')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('preparing', 'Tayyorlanmoqda'), ('delivering', 'Yetkazilmoqda'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holati')),
                ('placed_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Taxminiy yetkazish vaqti')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.customer', verbose_name='Mijoz')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurant.driver', verbose_name='Haydovchi')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.restaurant', verbose_name='Restoran')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Biriktirilgan'), ('picked_up', 'Olingan'), ('delivered', 'Yetkazilgan')], default='assigned', max_length=20, verbose_name='Holati')),
                ('pickup_at', models.DateTimeField(blank=True, null=True, verbose_name='Olish vaqti')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Yetkazilgan vaqt')),
                ('estimated_time', models.DurationField(blank=True, null=True, verbose_name='Taxminiy vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='restaurant.driver', verbose_name='Haydovchi')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='restaurant.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Yetkazib berish',
                'verbose_name_plural': 'Yetkazib berishlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdor')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bir dona narxi')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.dish', verbose_name='Taom')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='To‘lov summasi')),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('online', 'Onlayn')], max_length=20, verbose_name='To‘lov turi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', 'To‘langan'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='Holati')),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tranzaksiya raqami')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='To‘langan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='restaurant.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'To‘lov',
                'verbose_name_plural': 'To‘lovlar',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurant.restaurant', verbose_name='Restoran'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Baholash (1–5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant.customer', verbose_name='Mijoz')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='restaurant.driver', verbose_name='Haydovchi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant.order', verbose_name='Buyurtma')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant.restaurant', verbose_name='Restoran')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
