# Generated by Django 5.2.4 on 2025-10-22 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan vaqt')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_comments', to='restaurant.customer', verbose_name='Mijoz')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='restaurant.restaurant', verbose_name='Restoran')),
            ],
            options={
                'verbose_name': 'Restoran izohi',
                'verbose_name_plural': 'Restoranlar izohlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_likes', to='restaurant.customer', verbose_name='Mijoz')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='restaurant.restaurant', verbose_name='Restoran')),
            ],
            options={
                'verbose_name': 'Restoran layki',
                'verbose_name_plural': 'Restoranlar layklari',
                'unique_together': {('restaurant', 'customer')},
            },
        ),
    ]
